name: "LGTM Bot"
description: "A GitHub Action that posts a random LGTM image from LGTMOON when 'LGTM' or 'Approve' is detected."
author: "Your Name"
runs:
  using: "composite"
  steps:
    - name: Run LGTM Bot
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        OWNER: ${{ inputs.owner }}
        REPO: ${{ inputs.repo }}
        COMMENT_BODY: ${{ inputs.comment_body }}
        COMMENT_ID: ${{ inputs.comment_id }}
      run: |
        go run cmd/lgtm-action/main.go

inputs:
  github-token:
    description: "GitHub token for authentication"
    required: true
  owner:
    description: "Repository owner"
    required: true
  repo:
    description: "Repository name"
    required: true
  issue_number:
    description: "Issue or Pull Request number"
    required: true
  comment_body:
    description: "The content of the comment"
    required: true
  comment_id:
    description: "The ID of the comment"
    required: true


outputs:
  result:
    description: "The result of posting the LGTM image"
branding:
  icon: "smile"
  color: "blue"
