name: LGTM Bot

on:
  issue_comment:
    types: [created, edited]
  pull_request_review:
    types: [submitted, edited]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  lgtm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if comment contains 'lgtm'
        id: check_comment
        run: |
          echo "Comment body: ${{ github.event.comment.body }}"
          COMMENT_BODY="${{ github.event.comment.body }}"
          COMMENT_BODY_LOWER=$(echo "$COMMENT_BODY" | tr '[:upper:]' '[:lower:]')
          if [[ "$COMMENT_BODY_LOWER" != *"lgtm"* || "$COMMENT_BODY" == *"![LGTM]"* ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Run LGTM Bot Action
        if: steps.check_comment.outputs.skip == 'false'
        uses: db-r-hashimoto/lgtm_print@v0.0.2
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          owner: db-r-hashimoto
          repo: lgtm_print
          comment_body: ${{ github.event.comment.body }}
          comment_id: ${{ github.event.comment.id }}
