name: LGTM Bot

on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  lgtm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run LGTM Bot Action
        uses: ./
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
